### ISSUE TITLE
Error in new conventional commit message

### ISSUE THREAD

**Issue by sergiotejon** [sergiotejon/ai-commit#19]
```bash
❯ git ai-commit
time=2024-11-25T08:52:43.900+01:00 level=INFO msg="Querying Ollama..."
time=2024-11-25T08:52:43.900+01:00 level=INFO msg=Parameters server=http://localhost:11434 model=mistral

NewFiles(devbox.json, devbox.lock): Initialize development configuration files for new project setup

time=2024-11-25T08:52:45.158+01:00 level=ERROR msg="Invalid commit message" retry=0 error="illegal 'N' character in commit message type: col=00"

NewFiles(devbox.json, devbox.lock): Initialize development configuration files for new project setup

time=2024-11-25T08:52:45.930+01:00 level=ERROR msg="Invalid commit message" retry=1 error="illegal 'N' character in commit message type: col=00"

NewFiles(devbox.json, devbox.lock): Initialize development configuration files for new project setup

time=2024-11-25T08:52:46.704+01:00 level=ERROR msg="Invalid commit message" retry=2 error="illegal 'N' character in commit message type: col=00"
panic: illegal 'N' character in commit message type: col=00

goroutine 1 [running]:
github.com/sergiotejon/ai-commit/internal/cmd.init.func1(0x14000192400?, {0x105240973?, 0x4?, 0x105240977?})
        /Users/stejon/GolandProjects/ai-commit/internal/cmd/root.go:70 +0x5a0
github.com/spf13/cobra.(*Command).execute(0x1057cf000, {0x1400001e180, 0x0, 0x0})
        /Users/stejon/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x1057cf000)
        /Users/stejon/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/stejon/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/sergiotejon/ai-commit/internal/cmd.Execute()
        /Users/stejon/GolandProjects/ai-commit/internal/cmd/root.go:110 +0x24
main.main()
        /Users/stejon/GolandProjects/ai-commit/cmd/main.go:6 +0x1c
```

**Comment by sergiotejon** [comment]
Maybe, after setting `temperature = 0`, retrying does not generate a new commit message. Try setting `temperature` to 0.1.

**Comment by sergiotejon** [comment]
Setting `temperature` to 1 produces some good results. Perform more tests to fix the more accurate `temperature` setting and set it as the default value in the code.
